### ISSUE TITLE
Duplicate moduleService declaration in ModuleBatchProcessor

### ISSUE THREAD

**Issue by mikeumo** [scijava/batch-processor#19] opened 2019-11-14 23:27 UTC
The moduleService declaration in DynamicCommand (scijava-common) which ModuleBatchProcessor extends, has changed from "private" to "protected". Consequently,  the "private ModuleService moduleService" declaration in ModuleBatchProcessor throws "Invalid duplicate parameter" error. Solution: the declaration of moduleService in ModuleBatchProcessor should be removed.

**Comment by imagejan** [comment] 2019-11-15 07:24
Thanks for notifying us! I guess this is caused by a dependency skew in up-to-date Fiji installations after @ctrueden uploaded a new `scijava-common.jar` containing the fix in https://github.com/scijava/scijava-common/commit/089606b2f20f003e4fa22eeff573edb3ddbeaa1b.
I'll take care as soon as possible.

**Comment by imagejan** [comment] 2019-11-15 11:24
Fixed with https://github.com/scijava/batch-processor/commit/2a88b25192a4d44c79fe1bd7cc02176c16462a8f, which is included in [batch-processor-0.4.1.jar](https://maven.scijava.org/service/local/repositories/releases/content/org/scijava/batch-processor/0.4.1/batch-processor-0.4.1.jar) and <s>will soon be</s> **is now** uploaded to the *Java-8* update site.

**Closed as completed** 2019-11-15 13:35 UTC
